### ISSUE TITLE
Meta/Extension data

### ISSUE THREAD

**Issue by Jupeyy** [ddnet/ddnet-data-svg#10]
- Add a workflow to check for meta data?
- Only allow optimized SVGs?

**Comment by Jupeyy** [comment]
atleast looks like it doesnt contain too useful information, also asked Ravie, appearently grid data is lost as an example

**Comment by ChillerDragon** [comment]
We should keep grid data. Imo the svg's are working files and we do not use them in the final product or ship them. The rendered png is what is used. And the svg should be easy to work with for further updates/fixes.

**Comment by Jupeyy** [comment]
> We should keep grid data. Imo the svg's are working files and we do not use them in the final product or ship them.

Well thats not decided, and imo that will be the deciding factor :D

**Comment by ChillerDragon** [comment]
> > We should keep grid data. Imo the svg's are working files and we do not use them in the final product or ship them.
> 
> Well thats not decided, and imo that will be the deciding factor :D

It is easier to remove than to add them and for now there is no svg render engine planned so I would treat it as working files for now.

**Comment by Jupeyy** [comment]
@ChillerDragon , we should also check for embdedded images maybe, tho a few skins currently use them for the embedded credits
`xlink:href="data:image/png;base64,`

**Comment by ChillerDragon** [comment]
@Jupeyy anything missing to close this issue? Yes meta data is annoying and tools like inkscape add a lot of it. A simple edit causes huge diffs with different view port and inkscape version and so on. Yet I still think we should not add a meta data check to the CI or enforce optimized svgs.

That is because we agreed on not optimizing svgs in https://github.com/ddnet/ddnet-data-svg/issues/35
And because we also want to welcome contributions from designers. And a CI this strict can make them rage quit.

**Comment by Jupeyy** [comment]
I guess the main goal was to prevent users from leaking their names in the metadata.

And since we already prevent embedded images, which are ofc anti SVG, I am fine with closing
